// Environment variables loader for static deployment
// This file will be generated by Vercel build process with actual environment variables
// For local development, using default values

window.ENV = {
    VITE_FIREBASE_API_KEY: 'AIzaSyDl2WSk8Xj7X63cOyqJVTb2YICYlIL1I9o',
    VITE_FIREBASE_AUTH_DOMAIN: 'subscription-apps-demo.firebaseapp.com',
    VITE_FIREBASE_DATABASE_URL: 'https://subscription-apps-demo-default-rtdb.asia-southeast1.firebasedatabase.app/',
    VITE_FIREBASE_PROJECT_ID: 'subscription-apps-demo',
    VITE_FIREBASE_STORAGE_BUCKET: 'subscription-apps-demo.firebasestorage.app',
    VITE_FIREBASE_MESSAGING_SENDER_ID: '707083000716',
    VITE_FIREBASE_APP_ID: '1:707083000716:web:bc36622a201049134f54a9',
    VITE_FIREBASE_MEASUREMENT_ID: 'G-9HE0557ZF1',
    VITE_EXCHANGE_RATE_API_URL: 'https://api.exchangerate-api.com/v4/latest/MYR',
    VITE_DEFAULT_USER_ID: 'default-user'
};